-- phpMyAdmin SQL Dump
-- version 5.0.2
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: Nov 16, 2021 at 09:03 AM
-- Server version: 8.0.21
-- PHP Version: 7.3.21

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `blanks`
--

-- --------------------------------------------------------

--
-- Table structure for table `blanks`
--

DROP TABLE IF EXISTS `blanks`;
CREATE TABLE IF NOT EXISTS `blanks` (
  `mcq_id` int NOT NULL AUTO_INCREMENT,
  `mcq_subject` varchar(250) NOT NULL,
  `mcq_chapter` varchar(250) NOT NULL,
  `mcq_question` text NOT NULL,
  `mcq_option_1` varchar(300) NOT NULL,
  `mcq_option_2` varchar(300) NOT NULL,
  `mcq_option_3` varchar(300) NOT NULL,
  `mcq_option_4` varchar(300) NOT NULL,
  `mcq_option_1_comment` text NOT NULL,
  `mcq_option_2_comment` text NOT NULL,
  `mcq_option_3_comment` text NOT NULL,
  `mcq_option_4_comment` text NOT NULL,
  `mcq_creation_date` date NOT NULL,
  `answer` tinytext NOT NULL,
  `mcq_status` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`mcq_id`)
) ENGINE=MyISAM AUTO_INCREMENT=198 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `blanks`
--

INSERT INTO `blanks` (`mcq_id`, `mcq_subject`, `mcq_chapter`, `mcq_question`, `mcq_option_1`, `mcq_option_2`, `mcq_option_3`, `mcq_option_4`, `mcq_option_1_comment`, `mcq_option_2_comment`, `mcq_option_3_comment`, `mcq_option_4_comment`, `mcq_creation_date`, `answer`, `mcq_status`) VALUES
(1, 'Operating System', 'Basic', 'What is an operating system?', 'collection of programs that manages hardware resources', 'system service provider to the application programs', 'interface between the hardware and application programs', 'all of the mentioned', 'No', 'No', 'No', ' An Operating System acts as an intermediary between user/user applications/application programs and hardware. It is a program that manages hardware resources. It provides services to application programs.', '2021-11-11', 'D', 1),
(2, 'Computer Organization and Architecture', 'Pipelining', ' Any condition that causes a processor to stall is called as _________', 'Hazard', ' Page fault', 'System error', 'None of the mentioned', '', '', '', '', '2021-11-13', 'A', 1),
(3, 'Computer Organization and Architecture', 'Pipelining', 'The periods of time when the unit is idle is called as ________', 'Stalls', 'Bubbles', 'Hazards', 'Both A and B', '', '', '', '', '2021-11-13', 'D', 1),
(4, 'Computer Organization and Architecture', 'Pipelining', 'The contention for the usage of a hardware device is called ______', 'Structural hazard', ' Stalk', 'Deadlock', 'None of the mentioned', 'The processor contends for the usage of the hardware and might enter into a deadlock state.', '', '', '', '2021-11-13', 'A', 1),
(5, 'Computer Organization and Architecture', 'Pipelining', 'The situation wherein the data of operands are not available is called ______', 'Data hazard', 'Stock', 'Deadlock', 'Structural hazard', '', '', '', '', '2021-11-13', 'A', 1),
(6, 'Computer Organization and Architecture', 'Pipelining', 'The stalling of the processor due to the unavailability of the instructions is called as ___________', 'Control hazard', 'structural hazard', ' Input hazard', 'None of the mentioned', '', '', '', '', '2021-11-13', 'A', 1),
(7, 'Computer Organization and Architecture', 'Pipelining', 'The time lost due to the branch instruction is often referred to as ______', 'Latency', 'Delay', 'Branch penalty', 'None', 'No', 'No', 'For example, a branch instruction might be “If the result of the last ALU operation is negative, jump to location A in the program; otherwise, continue with the following instruction', 'No', '2021-11-13', 'C', 1),
(8, 'Computer Organization and Architecture', 'Pipelining', 'The pipeline bubbling is a method used to prevent data hazard and structural hazards', 'True', 'False', 'Both can be applied', 'none can be applied', 'The periods of time when the unit is idle is called a Bubble.', 'No', 'No', 'No', '2021-11-13', 'A', 1),
(9, 'Computer Organization and Architecture', 'Pipelining', '____________ method is used in centralized systems to perform out of order', 'Scorecard', 'Score boarding', 'Optimizing', 'Redundancy', 'No', ' In a scoreboard, the data dependencies of every instruction are logged. Instructions are released only when the scoreboard determines that there are no conflicts with previously issued and incomplete instructions.', 'No', 'No', '2021-11-13', 'B', 1),
(10, 'Computer Organization and Architecture', 'Pipelining', 'The algorithm followed in most of the systems to perform out of order execution is __________', 'Tomasulo algorithm', 'Score carding', 'Reader-writer algorithm', 'None of the mentioned', 'The Tomasulo algorithm is a hardware algorithm developed in 1967 by Robert Tomasulo from IBM. It allows sequential instructions that would normally be stalled due to certain dependencies to execute non-sequentially (out-of-order execution).', 'No', 'No', 'No', '2021-11-13', 'A', 1),
(11, 'Computer Organization and Architecture', 'Pipelining', 'The problem where process concurrency becomes an issue is called as ___________', 'Philosophers problem', 'Bakery problem', 'Bankers problem', 'Reader-writer problem', 'The Dining Philosopher Problem states that K philosophers seated around a circular table with one chopstick between each pair of philosophers. There is one chopstick between each philosopher. A philosopher may eat if he can pick up the two chopsticks adjacent to him. One chopstick may be picked up by any one of its adjacent followers but not both. They have 3 states eat,hungry, think', 'Before entering critical section process receive a ticket number', 'Suppose the number of account holders in a particular bank is \'n\', and the total money in a bank is \'T\'. If an account holder applies for a loan; first, the bank subtracts the loan amount from full cash and then estimates the cash difference is greater than T to approve the loan amount. These steps are taken because if another person applies for a loan or withdraws some amount from the bank, it helps the bank manage and operate all things without any restriction in the functionality of the banking system.', 'The readers-writers problem is used to manage synchronization so that there are no problems with the object data. For example - If two readers access the object at the same time there is no problem. However if two writers or a reader and writer access the object at the same time, there may be problems.\r\n\r\nTo solve this situation, a writer should get exclusive access to an object i.e. when a writer is accessing the object, no reader or writer may access it. However, multiple readers can access the object at the same time', '2021-11-13', 'D', 1),
(12, 'Computer Organization and Architecture', 'Cluster', 'The set of loosely connected computers are called as __________', 'LAN', 'WAN', 'WorkStation', 'Cluster', 'No', 'No', 'No', 'In a computer cluster all the participating computers work together on a particular task Cluster computing is the process of sharing the computation tasks among multiple computers and those computers or machines form the cluster. ... Some of the popular implementations of cluster computing are Google search engine, Earthquake Simulation, Petroleum Reservoir Simulation, and Weather Forecasting system.', '2021-11-13', 'D', 1),
(13, 'Computer Organization and Architecture', 'Cluster', 'Each computer in a cluster is connected using __________', 'UTP', 'Rj-45', 'STP', 'Coaxial-cable', 'No', 'No', 'No', 'No', '2021-11-13', 'B', 1),
(14, 'Computer Organization and Architecture', 'Cluster', 'The computer cluster architecture emerged as a result of _________', 'ISA', 'Workstation', 'Super Computer', 'Distributed System', 'No', 'No', 'No', 'A distributed system is a computer system spread out over a geographic area.', '2021-11-13', 'D', 1),
(15, 'Computer Organization and Architecture', 'Cluster', 'The software which governs the group of computers is __________', 'Driver Rd45', 'Interface UI', 'Clustering middleware', 'Distributor', 'No', 'No', 'he software helps to project a single system image to the user', 'No', '2021-11-13', 'C', 1),
(16, 'Computer Organization and Architecture', 'Cluster', 'The simplest form of a cluster is __________ approach.', 'Beowolf', 'Sequoia', 'Stone', 'None of the mentioned', 'A Beowulf cluster is a computer cluster of what are normally identical, commodity-grade computers networked into a small local area network with libraries and programs installed which allow processing to be shared among them. The result is a high-performance parallel computing cluster from inexpensive personal computer hardware', 'offer load balancing for databases', 'No', 'No', '2021-11-13', 'A', 1),
(17, 'Computer Organization and Architecture', 'Cluster', 'he cluster formation in which the work is divided equally among the systems is ______', 'Load-configuration', 'Load-Division', 'Light head', 'Both Load-configuration and Load-Division', 'This approach the work gets divided among the systems equally', 'No', 'No', 'No', '2021-11-13', 'A', 1),
(18, 'Computer Organization and Architecture', 'Cluster', ' In the client server model of the cluster _________ approach is used', 'Load Configuration', 'FIFO', 'Bankers Algorithm', 'Round Robin', 'No', 'No', 'No', 'No', '2021-11-13', 'D', 1),
(19, 'Computer Organization and Architecture', 'Cluster', 'The beowolf structure follows the __________ approach of a relationship between the systems.', 'Master-slave', 'Asynchronus', 'Synchronous', 'Isochronous', 'No', 'No', 'No', 'No', '2021-11-13', 'A', 1),
(20, 'Computer Organization and Architecture', 'Cluster', 'The most common modes of communication in clusters are ______', 'Message queues', 'Message passing interface', 'PVm', 'Both Message passing interface and PVm', 'No', 'No', 'No', 'Parrell Virtual Machine', '2021-11-13', 'D', 1),
(21, 'Computer Organization and Architecture', 'Cluster', 'The method followed in case of node failure, wherein the node gets disabled is _________', 'STONITH', 'Fibre Channel', 'Fencing', 'None of the mentioned', 'STONITH (\"Shoot The Other Node In The Head\" or \"Shoot The Offending Node In The Head\"), sometimes called STOMITH (\"Shoot The Other Member/Machine In The Head\"), is a technique for fencing in computer clusters. Fencing is the isolation of a failed node so that it does not cause disruption to a computer cluster.', 'No', 'No', 'No', '2021-11-13', 'A', 1),
(22, 'Computer Organization and Architecture', 'Cluster', 'VLIW stands for?', 'Very Long Instruction Word', 'Very Long Instruction Width', 'Very Large Instruction Word', 'Very Long Instruction Width', 'It is the architecture designed to perform multiple operations in parallel.', 'No', 'No', 'No', '2021-11-13', 'A', 1),
(23, 'Computer Organization and Architecture', 'Cluster', ' The important feature of the VLIW is _______', 'ILP', 'Cost Effectiveness', 'Performance', 'None of the mentioned', 'irregular instruction-level parallelism ', 'No', 'No', 'No', '2021-11-13', 'A', 1),
(24, 'Computer Organization and Architecture', 'Cluster', 'The main difference between the VLIW and the other approaches to improve performance is ___________', 'Cost effectiveness', 'Increase in performance', 'Lack of complex hardware design', 'All of the mentioned', 'No', 'No', 'The Pipe-lining and super-scalar architectures involved the usage of complex hardware circuits for the implementation', 'No', '2021-11-13', 'C', 1),
(25, 'Computer Organization and Architecture', 'Cluster', 'In VLIW the decision for the order of execution of the instructions depends on the program itself', 'True', 'False', 'either A or C', 'None', 'In other words, the order of execution of instructions has nothing to do with the physical hardware implementation of the system', 'No', 'No', 'No', '2021-11-13', 'A', 1),
(26, 'Computer Organization and Architecture', 'Cluster', 'The parallel execution of operations in VLIW is done according to the schedule determined by __________', ' Task scheduler', 'Interpreter', 'Compiler', 'Encoder', 'No', 'No', 'The compiler first checks the code for interdependencies and then determines the schedule for its execution', 'No', '2021-11-13', 'C', 1),
(27, 'Computer Organization and Architecture', 'Cluster', 'The VLIW processors are much simpler as they do not require of', 'Computational register', 'Complex logic circuits', 'SSD slots', 'Scheduling hardware', 'No', 'No', 'No', 'As the compiler only decides the schedule of execution the schedule is not required here', '2021-11-13', 'D', 1),
(28, 'Computer Organization and Architecture', 'Cluster', 'The VLIW architecture follows _____ approach to achieve parallelism', 'MISD', 'SISD', 'SIMD', 'MIMD', 'No', 'No', 'No', 'Single instruction stream, single data stream (SISD)\r\nSingle instruction stream, multiple data stream (SIMD)\r\nMultiple instruction stream, single data stream (MISD)\r\nMultiple instruction stream, multiple data stream (MIMD)', '2021-11-13', 'D', 1),
(29, 'Computer Organization and Architecture', 'Cluster', 'The following instruction is allowed in VLIW\r\nf12 = f0 * f4, f8 = f8 + f12, f0 = dm(i0, m3), f4 = pm(i8, m9);', 'True', 'False', 'Both', 'either', 'The above mentioned instruction is a complex 48 bit instruction used to perform operations on floating numbers', 'No', 'No', 'No', '2021-11-13', 'A', 1),
(30, 'Computer Organization and Architecture', 'Cluster', 'To compute the direction of the branch the VLIW uses _____________', 'Seekers', 'Heuristics', 'Direction counter', 'Compass', 'No', 'No', 'No', 'No', '2021-11-13', 'B', 1),
(31, 'Computer Organization and Architecture', 'Cluster', 'EPIC stands for?', ' Explicitly Parallel Instruction Computing', 'External Peripheral Integrating Component', 'External Peripheral Integrating Component', 'None', 'No', 'No', 'No', 'No', '2021-11-13', 'A', 1),
(32, 'Operating System', 'Scheduling', 'Which module gives control of the CPU to the process selected by the short-term scheduler?', 'dispatcher', 'interrupt', 'scheduler', 'none of the mentioned', 'No', 'No', 'An interrupt is a signal from a device attached to a computer or from a program within the computer that requires the operating system to stop and figure out what to do next. ... After the interrupt signal is sensed, the computer either resumes running the current program or begins running another program', 'No', '2021-11-14', 'A', 1),
(33, 'Operating System', 'Scheduling', 'The processes that are residing in main memory and are ready and waiting to execute are kept on a list called _____________', 'Job queue', 'Ready Queue', 'Execution Queue', 'Process queue', 'No', 'No', 'No', 'No', '2021-11-14', 'B', 1),
(34, 'Operating System', 'Scheduling', 'The interval from the time of submission of a process to the time of completion is termed as ____________', 'Waiting Time', 'Turnaround time', 'Response time', 'Through put', 'No', 'No', 'No', 'No', '2021-11-14', 'B', 1),
(35, 'Operating System', 'Scheduling', 'Which scheduling algorithm allocates the CPU first to the process that requests the CPU first?', 'first-come, first-served scheduling', 'shortest job scheduling', 'priority scheduling', ' none of the mentioned', 'No', 'No', 'No', 'No', '2021-11-14', 'A', 1),
(36, 'Operating System', 'Scheduling', ' In priority scheduling algorithm ____________', 'CPU is allocated to the process with highest priority', 'CPU is allocated to the process with lowest priority', 'Equal priority processes can not be scheduled', 'None of the mentioned', 'No', 'No', 'No', 'No', '2021-11-14', 'A', 1),
(37, 'Operating System', 'Scheduling', 'In priority scheduling algorithm, when a process arrives at the ready queue, its priority is compared with the priority of ____________', 'all process', 'currently running process', 'parent process', ' init process', 'No', 'No', 'No', 'No', '2021-11-14', 'B', 1),
(38, 'Operating System', 'Scheduling', 'Which algorithm is defined in Time quantum?', 'shortest job scheduling algorithm', 'round robin scheduling algorithm', 'priority scheduling algorithm', 'multilevel queue scheduling algorithm', 'No', 'No', 'No', 'No', '2021-11-14', 'B', 1),
(39, 'Operating System', 'Scheduling', 'Process are classified into different groups in ____________', 'shortest job scheduling algorithm', 'round robin scheduling algorithm', 'priority scheduling algorithm', 'multilevel queue scheduling algorithm', 'No', 'No', 'No', 'No', '2021-11-14', 'D', 1),
(40, 'Operating System', 'Scheduling', 'In multilevel feedback scheduling algorithm ____________', 'a process can move to a different classified ready queue', 'classification of ready queue is permanent', 'processes are not classified into groups', 'none of the mentioned', 'No', 'No', 'No', 'No', '2021-11-14', 'A', 1),
(41, 'Operating System', 'Scheduling', 'Which one of the following can not be scheduled by the kernel?', 'kernel level thread', 'user level thread', 'process', 'none of the mentioned', 'No', 'No', 'No', 'No', '2021-11-14', 'B', 1),
(42, 'Operating System', 'Scheduling', 'CPU scheduling is the basis of ___________', 'multiprocessor systems', 'multiprogramming operating systems\r\n', 'larger memory sized systems', 'none of the mentioned', 'No', 'No', 'No', 'No', '2021-11-14', 'B', 1),
(43, 'Operating System', 'Scheduling', 'With multiprogramming ______ is used productively', 'Time', 'Space', 'Money', 'All of the mentioned', 'No', 'No', 'No', 'No', '2021-11-14', 'A', 1),
(44, 'Operating System', 'Scheduling', 'What are the two steps of a process execution?', 'I/O & OS Burst', 'CPU & I/O Burst', 'Memory & I/O Burst', ' OS & Memory Burst', 'No', 'No', 'No', 'No', '2021-11-14', 'B', 1),
(45, 'Operating System', 'Scheduling', 'An I/O bound program will typically have ____________', 'a few very short CPU bursts', 'many very short I/O bursts', 'many very short CPU bursts', 'a few very short I/O bursts', 'No', 'No', 'No', 'No', '2021-11-14', 'C', 1),
(46, 'Operating System', 'Scheduling', 'A process is selected from the ______ queue by the ________ scheduler, to be executed.', 'blocked, short term', 'wait, long term', 'ready, short term', 'ready, long term', 'No', 'Long term select a process from secondary memory(job queue) and bring it to primary memory', 'Select a process from ready queue and assign it to CPU i t is fast', 'No', '2021-11-14', 'C', 1),
(47, 'Operating System', 'Scheduling', ' In the following cases non â€“ preemptive scheduling occurs?', 'When a process switches from the running state to the ready state', 'When a process goes from the running state to the waiting state', 'When a process goes from the running state to the waiting state\r\nc) When a process switches from the waiting state to the ready state', 'All of the mentioned', 'No', 'No', 'No', 'No', '2021-11-14', 'B', 1),
(48, 'Operating System', 'Scheduling', 'The switching of the CPU from one process or thread to another is called ____________\r\n', 'process switch', 'task switch\r\n', 'context switch', 'all of the mentioned', 'No', 'No', 'No', 'No', '2021-11-14', 'D', 1),
(49, 'Operating System', 'Scheduling', 'What is Dispatch latency?', 'the speed of dispatching a process from running to the ready state', 'the time of dispatching a process from running to ready state and keeping the CPU idle', 'the time to stop one process and start running another one', 'none', 'No', 'No', 'No', 'No', '2021-11-14', 'C', 1),
(50, 'Operating System', 'Scheduling', 'Scheduling is done so as to ____________', 'increase CPU Utlization', 'descrease CPU Utiliazation', 'Keep the CUP more idle', 'none of the mentioned', 'No', 'No', 'No', 'No', '2021-11-14', 'A', 1),
(51, 'Operating System', 'Scheduling', 'Scheduling is done so as to ____________', 'decrease the throughput', 'increase the throughput', 'increase the duration of a specific amount of work', 'none of the mentioned', 'No', 'No', 'No', 'No', '2021-11-14', 'B', 1),
(52, 'Operating System', 'Scheduling', 'What is Turnaround time?', 'the total waiting time for a process to finish execution', 'the total time spent in the ready queue', 'the total time spent in the running queue', 'the total time from the completion till the submission of a process', 'No', 'No', 'No', 'No', '2021-11-14', 'D', 1),
(53, 'Operating System', 'Scheduling', ' Scheduling is done so as to ____________', 'increase the turnaround time', 'decrease the turnaround time', 'keep the turnaround time same', 'there is no relation between scheduling and turnaround time', 'No', 'No', 'No', 'No', '2021-11-14', 'B', 1),
(54, 'Operating System', 'Scheduling', 'What is Waiting time?', 'the total time in the blocked and waiting queues', 'the total time spent in the ready queue', 'the total time spent in the running queue', 'the total time from the completion till the submission of a process', 'No', 'No', 'No', 'No', '2021-11-14', 'B', 1),
(55, 'Operating System', 'Scheduling', 'Scheduling is done so as to ____________', ' increase the waiting time', 'keep the waiting time the same', 'decrease the waiting time', 'none of the mentioned', 'No', 'No', 'No', 'No', '2021-11-14', 'C', 1),
(56, 'Operating System', 'Scheduling', ' What is Response time?', 'the total time taken from the submission time till the completion time', ' the total time taken from the submission time till the first response is produced', 'the total time taken from submission time till the response is output', 'none of the mentioned', 'No', 'No', 'No', 'No', '2021-11-14', 'B', 1),
(57, 'Operating System', 'Scheduling', 'What is Response time?', 'the total time taken from the submission time till the completion time', ' the total time taken from the submission time till the first response is produced', 'the total time taken from submission time till the response is output', 'none of the mentioned', 'No', 'No', 'No', 'No', '2021-11-14', 'B', 1),
(58, 'Operating System', 'Scheduling', 'Round robin scheduling falls under the category of ____________', 'Non-preemptive scheduling', ' Preemptive scheduling', 'All of the mentioned', 'None of the mentioned', 'No', 'No', 'No', 'No', '2021-11-14', 'B', 1),
(59, 'Operating System', 'Scheduling', 'With round robin scheduling algorithm in a time shared system ____________', 'using very large time slices converts it into First come First served scheduling algorithm', 'using very small time slices converts it into First come First served scheduling algorithm', 'using extremely small time slices increases performance', 'using very small time slices converts it into Shortest Job First algorithm', 'No', 'No', 'No', 'No', '2021-11-14', 'A', 1),
(60, 'Operating System', 'Scheduling', 'The portion of the process scheduler in an operating system that dispatches processes is concerned with ____________', 'assigning ready processes to CPU', 'assigning ready processes to waiting queue', 'assigning running processes to blocked queue', ' all of the mentioned', 'No', 'No', 'No', 'No', '2021-11-14', 'A', 1),
(61, 'Operating System', 'Scheduling', 'Complex Scheduling Algorithm', 'are very appropirate for very large computers', 'use minimal resuorces', 'use many resoureces', 'all of the mentioned', 'No', 'No', 'No', 'No', '2021-11-14', 'A', 1),
(62, 'Operating System', 'Scheduling', 'What is FIFO algorithm?', 'first executes the job that came in last in the queue', ' first executes the job that came in first in the queue', ' first executes the job that needs minimal processor', 'first executes the job that has maximum processor needs', 'No', 'No', 'No', 'No', '2021-11-14', 'B', 1),
(63, 'Operating System', 'Scheduling', 'The strategy of making processes that are logically runnable to be temporarily suspended is called ____________', 'Non pre emptive Scheduling', 'Pre emptive', 'Shortest Job First', 'First come first serve', 'No', 'No', 'No', 'No', '2021-11-14', 'B', 1),
(64, 'Operating System', 'Scheduling', 'What is Scheduling?', 'allowing a job to use the processor', ' making proper use of processor', 'all of the mentioned', 'none of the mentioned', 'No', 'No', 'No', 'No', '2021-11-14', 'A', 1),
(65, 'Operating System', 'Scheduling', 'There are 10 different processes running on a workstation. Idle processes are waiting for an input event in the input queue. Busy processes are scheduled with the Round-Robin time sharing method. Which out of the following quantum times is the best value for small response times, if the processes have a short runtime, e.g. less than 10ms?', 'tQ = 15ms', ' tQ = 40ms', 'tQ = 45ms', 'tQ = 50ms', 'IO bond process require smallest CPU time', 'No', 'No', 'No', '2021-11-14', 'A', 1),
(66, 'Operating System', 'Scheduling', 'Orders are processed in the sequence they arrive if _______ rule sequences the jobs', 'earliest due date', 'earliest due date', 'first come, first served', 'critical ratio', 'No', 'No', 'No', 'No', '2021-11-14', 'C', 1),
(67, 'Operating System', 'Scheduling', 'Which of the following algorithms tends to minimize the process flow time?', 'First come First served', 'Shortest Job First', 'Earliest Deadline First', ' Longest Job First', 'No', 'No', 'No', 'No', '2021-11-14', 'B', 1),
(68, 'Operating System', 'Scheduling', 'Under multiprogramming, turnaround time for short jobs is usually ________ and that for long jobs is slightly ___________', 'Lengthened; Shortened', 'Shortened; Lengthened', 'Shortened; Shortened', 'Shortened; Unchanged', 'No', 'No', 'No', 'No', '2021-11-14', 'B', 1),
(69, 'Operating System', 'Scheduling', 'Which of the following statements are true?  1)Shortest remaining time first scheduling may cause starvation. 2) Preemptive scheduling may cause starvation. 3) Round robin is better than FCFS in terms of response time', '1 only', 'I and 3 only', '1 2 and 3', ' None', 'No', 'No', 'No', 'No', '2021-11-14', 'C', 1),
(70, 'Operating System', 'Scheduling', 'Which is the most optimal scheduling algorithm?', ' FCFS â€“ First come First served', ' SJF â€“ Shortest Job First', 'RR â€“ Round Robin', 'None of the mentioned', 'No', 'No', 'No', 'No', '2021-11-14', 'B', 1),
(71, 'Operating System', 'Scheduling', 'The real difficulty with SJF in short term scheduling is ____________', 'it is too good an algorithm', 'knowing the length of the next CPU request', ' it is too complex to understand', 'none of the mentioned', 'No', 'No', 'No', 'No', '2021-11-14', 'B', 1),
(72, 'Operating System', 'Scheduling', 'Menu\r\n\r\nOperating System Questions and Answers â€“ CPU Scheduling Algorithms-2\r\nÂ« PrevNext Â»\r\nThis set of Operating System Questions and Answers for Freshers focuses on â€œCPU Scheduling Algorithms-2â€ and will also be useful for interview preparations for freshers.\r\n\r\n1. Which is the most optimal scheduling algorithm?\r\na) FCFS â€“ First come First served\r\nb) SJF â€“ Shortest Job First\r\nc) RR â€“ Round Robin\r\nd) None of the mentioned\r\nView Answer\r\n\r\nAnswer: b\r\nExplanation: None.\r\nadvertisement\r\n2. The real difficulty with SJF in short term scheduling is ____________\r\na) it is too good an algorithm\r\nb) knowing the length of the next CPU request\r\nc) it is too complex to understand\r\nd) none of the mentioned\r\nView Answer\r\n\r\nAnswer: b\r\nExplanation: None.\r\n3. The FCFS algorithm is particularly troublesome for ____________', 'Time sharing systems', 'Multiprogramming', 'Multiprocessor system', 'Operating systems', 'No', 'No', 'No', 'No', '2021-11-14', 'B', 1),
(73, 'Operating System', 'Scheduling', 'Consider the following set of processes, the length of the CPU burst time given in milliseconds. Process P1(6),P2(8),P3(7),P4(3)', 'The waiting time for process P1 is 3 ms', 'The waiting time for process P1 is 0 ms', 'The waiting time for process P1 is 16 ms', 'The waiting time for process P1 is 9 ms', 'No', 'No', 'No', 'No', '2021-11-14', 'A', 1),
(74, 'Operating System', 'Scheduling', 'Preemptive Shortest Job First scheduling is sometimes called ____________', 'Fast SJF Scheduling', 'EDF Scheduling - Earliest Deadlife First', 'HRRN Scheduling - Higheest Response Ratio Next', 'SRTN Scheduling - Shortest Remaining Time Next', 'No', 'No', 'No', 'No', '2021-11-14', 'D', 1),
(75, 'Operating System', 'Scheduling', 'An SJF algorithm is simply a priority algorithm where the priority is ____________', 'the predicted next CPU burst', ' the inverse of the predicted next CPU burst', 'the current CPU burst', 'anything the user wants', 'No', 'No', 'No', 'No', '2021-11-14', 'A', 1),
(76, 'Operating System', 'Scheduling', 'Choose one of the disadvantages of the priority scheduling algorithm?', ' it schedules in a very complex manner', 'its scheduling takes up a lot of time', ' it can lead to some low priority process waiting indefinitely for the CPU', 'none of the mentioned', 'No', 'No', 'No', 'No', '2021-11-14', '', 1),
(77, 'Operating System', 'Scheduling', 'What is â€˜Agingâ€™?', 'keeping track of cache contents', ' keeping track of what pages are currently residing in memory', 'keeping track of how many times a given page is referenced', 'increasing the priority of jobs to ensure termination in a finite time', 'No', 'No', 'No', 'No', '2021-11-14', 'D', 1),
(78, 'Operating System', 'Scheduling', 'A solution to the problem of indefinite blockage of low â€“ priority processes is ____________', ' Starvation', 'Wait queue', 'Ready queue', 'Aging', 'No', 'No', 'No', 'No', '2021-11-14', 'D', 1),
(79, 'Computer Organization and Architecture', 'Scheduling', 'Which of the following scheduling algorithms gives minimum average waiting time?', 'FCFS', 'SJF', 'Round â€“ robin', 'Priority', 'No', 'No', 'No', 'No', '2021-11-14', 'B', 1),
(80, 'Computer Networks', 'Introduction', 'The IETF standards documents are called ________', 'RFC', 'RCF', 'ID', 'DFC', 'RFC stands for Request For Comments and they are documents that describe methods, behaviors, research, or innovations applicable to the working of the Internet.', 'No', 'No', 'No', '2021-11-15', 'A', 1),
(81, 'Computer Networks', 'Introduction', 'In the layer hierarchy as the data packet moves from the upper to the lower layers, headers are', 'Added', 'Removed', 'Re arranged', 'Modified', 'Each layer adds its own header to the packet from the previous layer. For example, in the Internet layer, the IP header is added over the TCP header on the data packet that came from the transport layer', 'No', 'No', 'No', '2021-11-15', 'A', 1),
(82, 'Computer Networks', 'Introduction', 'The structure or format of data is called ___________', 'Syntax', 'Semantics', 'Struct', 'Formatting', ' The structure and format of data are defined using syntax. Semantics defines how a particular pattern to be interpreted, and what action is to be taken based on that interpretation. In programming languages, syntax of the instructions plays a vital role in designing of the program', 'No', 'No', 'No', '2021-11-15', 'A', 1),
(83, 'Computer Networks', 'Introduction', '. Communication between a computer and a keyboard involves ______________ transmission', 'Automatic', 'Half-duplex', 'Full-duplex', 'Simplex', 'No', 'No', 'No', 'No', '2021-11-15', 'D', 1),
(84, 'Computer Networks', 'Introduction', 'The first Network was called', 'CNNET', 'NSFNET', 'ASAPNET', 'ARPANET', 'No', 'No', 'No', 'ARPANET stands for Advanced Research Projects Agency Networks. It was the first network to be implemented which used the TCP/IP protocol in the year 1969', '2021-11-15', 'D', 1),
(85, 'Computer Networks', 'Introduction', 'A _______ is the physical path over which a message travels', 'Path', 'Medium', 'Protocol', 'Route', 'No', 'Messages travel from sender to receiver via a physical path called the medium using a set of methods/rules called protocol. Mediums can be guided (wired) or unguided (wireless).', 'No', 'No', '2021-11-15', 'B', 1),
(86, 'Computer Networks', 'Introduction', 'Which organization has authority over interstate and international commerce in the communications field?', 'ITU-T', 'IEEE', 'FCC', 'ISOC', 'No', 'No', 'CC is the abbreviation for Federal Communications Commission. FCC is responsible for regulating all interstate communications originating or terminating in USA. It was founded in the year 1934', 'No', '2021-11-15', 'C', 1),
(87, 'Computer Networks', 'Introduction', 'Which of this is not a network edge device?', 'PC', 'Smartphones', 'Servers', 'Switch', 'No', 'No', 'No', 'Network edge devices refer to host systems, which can host applications like web browser. A switch can’t operate as a host, but as a central device which can be used to manage network communication.', '2021-11-15', 'D', 1),
(88, 'Computer Networks', 'Introduction', 'A _________ set of rules that governs data communication', 'Protocols', 'Standards', 'RFCs', 'Servers', 'protocol refers to a set of rules and regulations that allow a network of nodes to transmit and receive information. Each layer in the network model has a protocol set, for example, the transport layer has TCP and UDP protocol', 'No', 'No', 'No', '2021-11-15', 'A', 1),
(89, 'Computer Networks', 'Introduction', ' Three or more devices share a link in ________ connection', 'Unipoint', 'Multipoint', 'Point to point', 'Simplex', 'No', ' multipoint communication is established when three or many network nodes are connected to each other. Frame relay, Ethernet and ATM are some examples of multipoint connections.\r\nSanfoundry Global Educ', 'No', 'No', '2021-11-15', 'B', 1),
(90, 'Computer Networks', 'Introduction', 'When collection of various computers seems a single coherent system to its client, then it is called _________', 'computer network', 'distributed system', 'networking system', 'mail system', 'No', 'No', 'No', 'No', '2021-11-15', 'B', 1),
(91, 'Computer Networks', 'Introduction', 'Two devices are in network if __________', 'a process in one device is able to exchange information with a process in another device', 'a process is running on both devices', 'PIDs of the processes running of different devices are same', 'a process is active and another is inactive', 'No', 'No', 'No', 'No', '2021-11-15', 'A', 1),
(92, 'Computer Networks', 'Introduction', 'Which of the following computer networks is built on the top of another network?', 'Prior network', 'Chief network', 'Prime network', 'Overlay network', 'No', 'No', 'No', 'An overlay network is a computer network that is built on top of another network. Some examples of an overlay network are Virtual Private Networks (VPN) and Peer-to-Peer Networks (P2P).', '2021-11-15', 'D', 1),
(93, 'Computer Networks', 'Introduction', 'In computer network nodes are _________', 'the computer that originates the data', 'the computer that routes the data', 'the computer that terminates the data', 'all of the mentioned', 'No', 'No', 'No', 'In a computer network, a node can be anything that is capable of sending data or receiving data or even routing the data to its destination. Routers, Computers and Smartphones are some examples of network nodes.', '2021-11-15', 'D', 1),
(94, 'Computer Networks', 'Introduction', ' Communication channel is shared by all the machines on the network in ________', 'Broadcast network', 'Unicast network', 'Multicast network', 'Anycast network', 'No', 'No', 'No', 'No', '2021-11-15', 'A', 1),
(95, 'Computer Networks', 'Introduction', 'Bluetooth is an example of __________', 'Personal Area Network', 'Local area network', 'Wide area network', 'Virtual private network', 'No', 'No', 'No', 'No', '2021-11-15', 'A', 1),
(96, 'Computer Networks', 'Introduction', 'Bluetooth is a wireless technology it transfer data up to a distance of 10 meter its frequency band is', '2.1', '2.45', '3.4', '4.3', 'No', 'No', 'No', 'No', '2021-11-15', 'B', 1),
(97, 'Computer Networks', 'Introduction', 'A __________ is a device that forwards packets between networks by processing the routing information included in the packet.', 'Bridge', 'Firewall', 'Router', 'Hub', 'No', 'No', 'No', 'No', '2021-11-15', 'C', 1),
(98, 'Computer Networks', 'Introduction', 'A list of protocols used by a system, one protocol per layer, is called ________', 'Protocol architecture', 'Protocol stack', 'Protocol suite', 'Protocol system', 'No', 'A protocol stack refers to a group of protocols that are running concurrently that are employed for the implementation of network protocol suite. Each layer in the network model has to use one specific protocol from the protocol stack.', 'No', 'No', '2021-11-15', 'B', 1),
(99, 'Computer Networks', 'Introduction', 'Network congestion occurs _________', 'when a system terminates', 'when connection between two nodes terminates', 'in case of traffic overloading', 'in case of transfer failure', 'No', 'No', 'No', 'No', '2021-11-15', 'C', 1),
(100, 'Computer Networks', 'Introduction', 'Which of the following networks extends a private network across public networks', 'Local area network', 'virtual private network', 'enterprise private network', 'storage area network', 'No', ' A virtual private network extends a private network across a public network, and enables users to send and receive data across shared or public networks as if their computing devices were directly connected to the private network.VPN provides enhanced security and online anonymity to users on the internet. It is also used to unblock websites which are unavailable in certain regions', 'No', 'No', '2021-11-15', 'B', 1),
(101, 'Computer Networks', 'Introduction', 'Which of this is not a constituent of residential telephone line?', 'A high-speed downstream channel', 'A medium-speed downstream channel', 'A low-speed downstream channel', 'An ultra-high speed downstream channel', 'No', 'No', 'A low-speed downstream channel is not a constituent of a residential telephone line. But it might be just a two-way telephone channel. Internet can be provided through a high-speed downstream channel in a residential telephone line.', 'No', '2021-11-15', 'C', 1),
(102, 'Computer Networks', 'Introduction', ' DSL telcos provide which of the following services?', 'Wired phone access', 'ISP', 'Wired Phone access and ISP', 'Network routing and ISP', 'No', 'No', 'No', 'No', '2021-11-15', 'C', 1),
(103, 'Computer Networks', 'Introduction', 'The function of DSLAM is to __________', 'Convert analog signals into digital signals', 'Convert digital signals into analog signals', 'Amplify digital signals', 'De-amplify digital signals', 'DSLAM stands for Digital Subscriber Line Access Multiplexer and it’s used by Telcos to convert the analog signals to digital signals for the purpose of providing internet. The DSLAM located in a telco’s Central Office does this function', 'No', 'No', 'No', '2021-11-15', 'A', 1),
(104, 'Computer Networks', 'Introduction', 'Which of the following terms is not associated with DSL?', 'DSLAM', 'CO', 'Splitter', 'CMTS', 'No', 'No', 'No', 'CMTS stands for Cable modem termination system. It is used in cable internet access. In cable internet access, internet is not provided through telephone lines and the companies that provide such connections don’t necessarily provide telephone access.', '2021-11-15', 'D', 1),
(105, 'Computer Networks', 'Introduction', 'HFC contains _______', 'Fibre Cable', 'Coaxial Cable', 'A combination of Fibre and Coaxial Cable', 'Twisted Pair Cable', 'No', 'No', ' Hybrid fiber-coaxial (HFC) is a telecommunications industry term for a broadband network that combines optical fiber and coaxial cable. It has been popularly used since the early 1990s. It is stronger than the optical fiber cables and faster than the co-axial cables.', 'No', '2021-11-15', 'C', 1),
(106, 'Computer Networks', 'Introduction', 'Which of the following statements is not applicable for cable internet access?', ' It is a shared broadcast medium', 'It includes HFCs', 'Cable modem connects home PC to Ethernet port', 'Analog signal is converted to digital signal in DSLAM', 'No', 'No', 'No', 'CMTS stands for Cable modem termination system. In cable access analog signal is converted to digital signal by CMTS. In cable internet access, internet is not provided through telephone lines. DSLAM is used by Telecom companies', '2021-11-15', 'D', 1),
(107, 'Computer Networks', 'Introduction', 'Among the optical-distribution architectures that are essentially switched ethernet is __________', 'AON', 'PON', 'NON', 'MON', 'AON stands for Active optical networks which are essentially switched Ethernets. Each user has his/her own dedicated optical fiber line connecting to the ISP in an AON', 'No', 'No', 'No', '2021-11-15', 'A', 1),
(108, 'Computer Networks', 'Introduction', 'StarBand provides __________', 'FTTH internet access', 'Cable accesss', 'Telephone acess', 'Satellite access', 'No', 'No', 'No', ' StarBand was a two-way satellite broadband Internet service available in the U.S. from 2000–2015. It was discontinued from September 30 2015 due to increasing competition from other ISPs', '2021-11-15', 'D', 1),
(109, 'Computer Networks', 'Introduction', 'Which of the following factors affect transmission rate in DSL?', 'The gauge of the twisted-pair line', 'Degree of electrical interfernece', 'Shadow fading', 'The gauge of the twisted-pair line and degree of electrical interference', 'No', 'No', 'No', 'Because DSL is made of twisted wire copper pair, the gauge of twisted pair line i.e. the protection and electrical interference would affect the transmission rate in DSL. Unlike DSL, FTTP is not really affected by these factors.', '2021-11-15', 'D', 1),
(110, 'Computer Networks', 'Introduction', 'How many layers are present in the Internet protocol stack (TCP/IP model)?', '5', '7', '6', '10', 'No', 'No', 'No', 'No', '2021-11-15', 'A', 1),
(111, 'Computer Networks', 'Introduction', 'The number of layers in ISO OSI reference model is __________', '5', '7', '6', '10', 'No', 'No', 'No', 'No', '2021-11-15', 'B', 1),
(112, 'Computer Networks', 'Introduction', 'Which of the following layers is an addition to OSI model when compared with TCP IP model?', 'Application layer', 'Presentation layer', 'Session layer', 'Session and Presentation layer', 'No', 'No', 'No', 'No', '2021-11-15', 'D', 1),
(113, 'Computer Networks', 'Introduction', 'Application layer is implemented in ____________', 'End System', 'NIC', 'Ethernet', 'Packet Transport', 'No', 'No', 'No', 'No', '2021-11-15', 'A', 1),
(114, 'Computer Networks', 'Introduction', ' Transport layer is implemented in ______________', ' End system', 'NIC', 'Ethernet', 'Signal transmission', 'Not only application layer, but presentation layer, session layer and transport layer are also implemented in the end system. The layers below are implemented outside the end system, for example, the network layer is implemented on the routers and the physical layer is implemented for the medium.', 'No', 'No', 'No', '2021-11-15', '', 1),
(115, 'Computer Networks', 'Introduction', ' The functionalities of the presentation layer include ____________', 'Data compression', 'Data encryption', 'Data description', ' All of the mentioned', 'No', 'No', 'No', 'Some functions of the presentation layer include character-code translation, data conversion, data encryption and decryption, and data translation. It connects the application layer with the layers below converting the human readable text and media to machine readable format and vice', '2021-11-15', '', 1),
(116, 'Computer Networks', 'Introduction', 'Delimiting and synchronization of data exchange is provided by __________', 'Application layer', 'Session layer', 'Transport layer', 'Link layer', 'No', 'The session layer provides the mechanism for opening, closing and managing a session between end-user application processes. The session layer 5 is responsible for establishing managing synchronizing and terminating sessions. In TCP/IP protocol stack, the functions of the session layer are handled by the transport layer itself and thus the session layer is missing from the TCP/IP model', 'No', 'No', '2021-11-15', 'B', 1),
(117, 'Computer Networks', 'Introduction', ' In OSI model, when data is sent from device A to device B, the 5th layer to receive data at B is _________', 'Application layer', ' Transport layer', 'Link layer', 'Session layer', 'No', 'No', 'No', 'No', '2021-11-15', 'A', 1),
(118, 'Computer Networks', 'Introduction', 'In TCP IP Model, when data is sent from device A to device B, the 5th layer to receive data at B is ____________', 'Application layer', 'Transport layer', 'Link layer', 'Session layer', 'No', 'No', 'No', 'No', '2021-11-15', 'A', 1),
(119, 'Computer Networks', 'Introduction', 'In the OSI model, as a data packet moves from the lower to the upper layers, headers are _______', 'Added', 'Removed', 'Rearranged', 'Randomized', 'No', 'No', 'No', 'No', '2021-11-15', 'B', 1),
(120, 'Computer Networks', 'Introduction', 'OSI stands for __________', 'open system interconnection', 'operating system interface', 'optical service implementation', 'open service Internet', 'No', 'No', 'No', 'No', '2021-11-15', 'A', 1),
(121, 'Computer Networks', 'Introduction', 'The number of layers in ISO OSI reference model is __________', '4', '5', '6', '7', 'No', 'No', 'No', 'No', '2021-11-15', 'D', 1),
(122, 'Computer Networks', 'Introduction', ' Which layer is used to link the network support layers and user support layers?', ' session layer', 'data link layer', 'transport layer', 'network layer', 'No', 'No', 'No', 'No', '2021-11-15', 'C', 1),
(123, 'Computer Networks', 'Introduction', 'Which address is used on the internet for employing the TCP/IP protocols?', 'a) physical address and logical address', 'port address', 'specific address', 'all of the mentioned', 'No', 'No', 'No', 'The physical, logical, port and specific addresses are used in TCP/IP protocol. All the addressing schemes, that is physical (MAC) and logical address, port address and specific address are employed in both TCP/IP model and OSI model. In TCP/IP, the addresses are more focused on the internet implementation of these addresses', '2021-11-15', '', 1),
(124, 'Computer Networks', 'Introduction', 'TCP/IP model was developed _____ the OSI model.', ' prior to', ' after', 'simultaneous to', 'with no link to', 'Several TCP/IP prototypes were developed at multiple research centers between 1978 and 1983, whereas OSI reference model was developed in the year 1984. TCP/IP was developed with the intention to create a model for the Internet while OSI was intended to be a general network model', 'No', 'No', 'No', '2021-11-15', 'A', 1),
(125, 'Computer Networks', 'Introduction', 'Which layer is responsible for process to process delivery in a general network model?', 'network layer', ' transport layer', 'session layer', 'data link layer', 'No', 'The role of Transport layer (Layer 4) is to establish a logical end to end connection between two systems in a network. The protocols used in Transport layer is TCP and UDP. The transport layer is responsible for segmentation of the data. It uses ports for the implementation of process-to-process delivery.\r\n', 'No', 'No', '2021-11-15', 'B', 1),
(126, 'Computer Networks', 'Introduction', 'Which address is used to identify a process on a host by the transport layer?', 'physical address', ' logical address', ' port address', 'specific address', 'No', 'No', 'A port number is a way to identify a specific process to which an Internet or other network message is to be forwarded when it arrives at a server. Some examples of port numbers are port 20 which is used for FTP data, port 22 which is used for SSH remote login ,and port 23 which is used for TELNET', 'No', '2021-11-15', '', 1),
(127, 'Computer Networks', 'Introduction', 'Which layer provides the services to user?', 'application layer', 'session layer', 'presentation layer', ' physical layer', 'No', 'No', 'No', 'No', '2021-11-15', 'A', 1),
(128, 'Computer Networks', 'Introduction', 'Transmission data rate is decided by ____________', 'network layer', 'physical layer', ' data link layer', ' transport layer', 'No', 'No', 'No', 'No', '2021-11-15', 'B', 1),
(129, 'Computer Networks', 'Network Layers', 'The physical layer is concerned with ___________', 'bit-by-bit delivery', 'process to process delivery', 'application to application delivery', 'port to port delivery', 'No', 'No', 'No', 'No', '2021-11-15', 'A', 1),
(130, 'Computer Networks', 'Network Layers', 'Bits can be sent over guided and unguided media as analog signal by', 'digital modulation', 'amplitude modulation', ' frequency modulation', ' phase modulation', 'No', 'No', 'No', 'No', '2021-11-15', '', 1),
(131, 'Computer Networks', 'Network Layers', 'The portion of physical layer that interfaces with the media access control sublayer is called ___________', 'physical signaling sublayer', 'physical data sublayer', 'physical address sublayer', 'physical transport sublayer', 'The physical layer is divided into two sublayers: \r\nthe Physical Layer Convergence Procedure (PLCP) sublayer \r\nand the Physical Medium Dependent (PMD) sublayer. \r\nThe PLCP (Figure 10-1) is the glue between the frames of the MAC and the radio transmissions in the air.\r\nPLCP adds its own header to any transmitted frames. \r\nThe PMD is responsible for transmitting any bits it receives from the PLCP into the air using the antenna.', 'No', 'No', 'The portion of physical layer that interfaces with the medium access control sublayer is Physical Signaling Sublayer. The main function of this layer is character encoding, reception, decoding and performs optional isolation functions. It handles which media connection the signal should be forwarded to physically.', '2021-11-15', 'A', 1),
(132, 'Computer Networks', 'Network Layers', 'The physical layer provides __________', 'mechanical specifications of electrical connectors and cables', 'electrical specification of transmission line signal level', ' specification for IR over optical fiber', ' all of the mentioned', 'No', 'No', 'No', 'No', '2021-11-15', 'D', 1),
(133, 'Computer Networks', 'Network Layers', 'In asynchronous serial communication the physical layer provides ___________', 'start and stop signaling', 'flow control', ' both start & stop signaling and flow control', 'only start signaling', 'No', 'No', 'No', 'No', '2021-11-15', 'C', 1),
(134, 'Computer Networks', 'Network Layers', 'The physical layer translates logical communication requests from the ______ into hardware specific operation', 'data link layer', 'network layer', 'transport layer', 'application layer', 'No', 'No', 'No', 'No', '2021-11-15', 'A', 1),
(135, 'Computer Networks', 'Network Layers', 'A single channel is shared by multiple signals by ____________', 'analog modulation', 'digital modulation', 'multiplexing', 'phase modulation', 'No', 'No', 'No', 'No', '2021-11-15', 'C', 1),
(136, 'Computer Networks', 'Network Layers', 'Wireless transmission of signals can be done via ___________', ' radio waves', 'microwaves', ' infrared', 'all of the mentioned', 'No', 'No', 'No', 'Wireless transmission is carried out by radio waves, microwaves and IR waves. These waves range from 3 Khz to above 300 Ghz and are more suitable for wireless transmission. Radio waves can penetrate through walls and are used in radio communications, microwaves and infrared (IR) waves cannot penetrate through walls and are used for satellite communications and device communications respectively', '2021-11-15', 'D', 1);
INSERT INTO `blanks` (`mcq_id`, `mcq_subject`, `mcq_chapter`, `mcq_question`, `mcq_option_1`, `mcq_option_2`, `mcq_option_3`, `mcq_option_4`, `mcq_option_1_comment`, `mcq_option_2_comment`, `mcq_option_3_comment`, `mcq_option_4_comment`, `mcq_creation_date`, `answer`, `mcq_status`) VALUES
(137, 'Computer Networks', 'Network Layers', ' The data link layer takes the packets from _________ and encapsulates them into frames for transmission', 'network layer', 'physical layer', 'transport layer', 'application layer', 'In computer networks, the data from application layer is sent to transport layer and is converted to segments. These segments are then transferred to the network layer and these are called packets. These packets are then sent to data link layer where they are encapsulated into frames. These frames are then transferred to physical layer where the frames are converted to bits. Error control and flow control data is inserted in the frames at the data link layer.', 'No', 'No', 'No', '2021-11-15', 'A                                                                                             ', 1),
(138, 'Computer Networks', 'Network Layers', 'Which of the following tasks is not done by data link layer?', 'framing', 'error control', 'flow control', 'channel coding', 'No', 'No', 'No', 'Channel coding is the function of physical layer. Data link layer mainly deals with framing, error control and flow control. Data link layer is the layer where the packets are encapsulated into frames', '2021-11-15', 'D', 1),
(139, 'Computer Networks', 'Network Layers', 'Which sublayer of the data link layer performs data link functions that depend upon the type of medium?', 'logical link control sublayer', 'media access control sublayer', 'network interface control sublayer', 'error control sublayer', 'No', 'Media access control (MAC) deals with transmission of data packets to and from the network-interface card, and also to and from another remotely shared channel. The MAC sublayer also prevents collision using protocols like CSMA/CD', 'No', 'No', '2021-11-15', 'B', 1),
(140, 'Computer Networks', 'Network Layers', 'Header of a frame generally contains ______________', 'synchronization bytes', 'addresses', 'frame identifier', ' all of the mentioned', 'No', 'No', 'No', 'In a frame, the header is a part of the data that contains all the required information about the transmission of the file. It contains information like synchronization bytes, addresses, frame identifier etc. It also contains error control information for reducing the errors in the transmitted frames.', '2021-11-15', 'D', 1),
(141, 'Computer Networks', 'Network Layers', 'Automatic repeat request error management mechanism is provided by', 'logical link control sublayer', 'network interface control sublayer', 'media access control sublayer', 'application access control sublayer', 'The logical link control is a sublayer of data link layer whose main function is to manage traffic, flow and error control. The automatic repeat request error management mechanism is provided by the LLC when an error is found in the received frame at the receiverâ€™s end to inform the sender to re-send the frame.', 'No', 'No', 'No', '2021-11-15', 'A', 1),
(142, 'Computer Networks', 'Network Layers', 'When 2 or more bits in a data unit has been changed during the transmission, the error is called ____________', ' random error', 'burst error', 'inverted error', 'double error', 'No', 'When a single bit error occurs in a data, it is called single bit error. When more than a single bit of data is corrupted or has error, it is called burst error. If a single bit error occurs, the bit can be simply repaired by inverting it, but in case of a burst error, the sender has to send the frame again.', 'No', 'No', '2021-11-15', '', 1),
(143, 'Computer Networks', 'Network Layers', 'CRC stands for __________', 'cyclic redundancy check', 'code repeat check', 'code redundancy check', ' cyclic repeat check', 'Cyclic redundancy check is a code that is added to a data which helps us to identify any error that occurred during the transmission of the data. CRC is only able to detect errors, not correct them. CRC is inserted in the frame trailer.', 'No', 'No', 'No', '2021-11-15', 'A', 1),
(144, 'Computer Networks', 'Network Layers', 'Which of the following is a data link protocol?', 'ethernet', ' point to point protocol', 'hdlc', 'all of the mentioned', 'No', 'No', 'No', 'There are many data link layer protocols. Some of them are SDLC (synchronous data link protocol), HDLC (High level data link control), SLIP (serial line interface protocol), PPP (Point to point protocol) etc. These protocols are used to provide the logical link control function of the Data Link Layer.', '2021-11-15', 'D', 1),
(145, 'Computer Networks', 'Network Layers', 'Which of the following is the multiple access protocol for channel access control?', 'CSMA/CD', ' CSMA/CA', ' Both CSMA/CD & CSMA/CA', 'HDLC', 'No', 'No', 'No', 'No', '2021-11-15', 'C', 1),
(146, 'Computer Networks', 'Network Layers', 'The technique of temporarily delaying outgoing acknowledgements so that they can be hooked onto the next outgoing data frame is called ____________', 'piggybacking', 'cyclic redundancy check', ' fletcherâ€™s checksum', 'parity check', 'No', 'No', 'No', 'No', '2021-11-15', 'A', 1),
(147, 'Computer Networks', 'Network Layers', 'The network layer is concerned with __________ of data', 'Bits', 'Frames', 'Packets', 'Bytes', 'No', 'No', 'In computer networks, the data from the application layer is sent to the transport layer and is converted to segments. These segments are then transferred to the network layer and these are called packets. These packets are then sent to data link layer where they are encapsulated into frames. These frames are then transferred to physical layer where the frames are converted to bits', 'No', '2021-11-15', 'C', 1),
(148, 'Computer Networks', 'Network Layers', 'Which one of the following is not a function of network layer?', 'Routing', 'Inter-networking', 'congestion control', 'error control', 'No', 'No', 'No', 'In the OSI model, network layer is the third layer and it provides data routing paths for network communications. Error control is a function of the data link layer and the transport layer', '2021-11-15', 'D', 1),
(149, 'Computer Networks', 'Network Layers', 'A 4 byte IP address consists of __________', 'only network address', 'only host address', 'network address & host address', 'network address & MAC address', 'No', 'No', 'An ip address which is 32 bits long, that means it is of 4 bytes and is composed of a network and host portion and it depends on address class. The size of the host address and network address depends upon the class of the address in classful IP addressing.', 'No', '2021-11-15', 'C', 1),
(150, 'Computer Networks', 'Network Layers', 'In virtual circuit network each packet contains ___________', ' full source and destination address', 'a short VC number', 'only source address', 'only destination address', 'No', 'A short VC number also called as VCID (virtual circuit identifier) is a type of identifier which is used to distinguish between several virtual circuits in a connection oriented circuit switched network. Each virtual circuit is used to transfer data over a larger packet switched network', 'No', 'No', '2021-11-15', 'B', 1),
(151, 'Computer Networks', 'Network Layers', 'Which of the following routing algorithms can be used for network layer design?', 'shortest path algorithm', 'distance vector routing', ' link state routing', ' all of the mentioned', 'No', 'No', 'No', 'No', '2021-11-15', 'D', 1),
(152, 'Computer Networks', 'Network Layers', ' Which of the following is not correct in relation to multi-destination routing?', ' is same as broadcast routing', 'contains the list of all destinations', 'data is not sent by packets', 'there are multiple receivers', 'No', 'No', 'In multi-destination routing, there is more than one receiver and the route for each destination which is contained in a list of destinations is to be found by the routing algorithm. Multi-destination routing is also used in broadcasting.', 'No', '2021-11-15', 'C', 1),
(153, 'Computer Networks', 'Network Layers', 'A subset of a network that includes all the routers but contains no loops is called ________', 'Spanning tree', 'Spider structure', 'Spider tree', 'Special tree', ' Spanning tree protocol (STP) is a network protocol that creates a loop free logical topology for ethernet networks. It is a layer 2 protocol that runs on bridges and switches. The main purpose of STP is to ensure that you do not create loops when you have redundant paths in your network', 'No', 'No', 'No', '2021-11-15', 'A', 1),
(154, 'Computer Networks', 'Network Layers', 'Which one of the following algorithm is not used for congestion control?', 'traffic aware routing', 'admission control', 'load shedding', ' routing information protocol', 'No', 'No', 'No', 'No', '2021-11-15', 'D', 1),
(155, 'Computer Networks', 'Network Layers', 'The network layer protocol for internet is __________', 'ethernet', 'internet protocol', ' hypertext transfer protocol', ' file transfer protocol', 'No', 'There are several protocols used in Network layer. Some of them are IP, ICMP, CLNP, ARP, IPX, HRSP etc. Hypertext transfer protocol is for application layer and ethernet protocol is for data link layer', 'No', 'No', '2021-11-15', 'B', 1),
(156, 'Computer Networks', 'Network Layers', 'ICMP is primarily used for __________', 'error and diagnostic functions', 'addressing', 'forwarding', 'routing', 'ICMP abbreviation for Internet Control Message Protocol is used by networking devices to send error messages and operational information indicating a host or router cannot be reached. ICMP operates over the IP packet to provide error reporting functionality as IP by itself cannot report errors', 'No', 'No', 'No', '2021-11-15', 'A', 1),
(157, 'Computer Networks', 'Network Layers', 'Transport layer aggregates data from different applications into a single stream before passing it to ____________', 'Network Layer', 'Data link layer', 'Application layer', 'Physical layer', 'The flow of data in the OSI model flows in following manner Application -> Presentation -> Session -> Transport -> Network -> Data Link -> Physical. Each and every layer has its own set of functions and protocols to ensure efficient network performance', 'No', 'No', 'No', '2021-11-16', 'A', 1),
(158, 'Computer Networks', 'Network Layers', 'Which of the following are transport layer protocols used in networking?', 'TCP and FTP', 'UDP and HTTP', 'TCP and UDP', 'HTTP and FTP', 'No', 'No', ' Both TCP and UDP are transport layer protocol in networking. TCP is an abbreviation for Transmission Control Protocol and UDP is an abbreviation for User Datagram Protocol. TCP is connection oriented whereas UDP is connectionless', 'No', '2021-11-16', 'C', 1),
(159, 'Computer Networks', 'Network Layers', 'User datagram protocol is called connectionless because _____________', 'all UDP packets are treated independently by transport layer', 'it sends data as a stream of related packets', 'it is received in the same order as sent order', ' it sends data very quickly', 'UDP is an alternative for TCP and it is used for those purposes where speed matters most whereas loss of data is not a problem. UDP is connectionless whereas TCP is connection oriented.', 'No', 'No', 'No', '2021-11-16', 'A', 1),
(160, 'Computer Networks', 'Network Layers', ' Transmission control protocol ___________', 'is a connection-oriented protocol', 'uses a three way handshake to establish a connection', 'receives data from application as a single stream', 'all of the mentioned', 'No', 'No', 'No', 'TCP provides reliable and ordered delivery of a stream of bytes between hosts communicating via an IP network. Major internet applications like www, email, file transfer etc rely on TCP. TCP is connection oriented and it is optimized for accurate delivery rather than timely delivery', '2021-11-16', 'D', 1),
(161, 'Computer Networks', 'Network Layers', ' An endpoint of an inter-process communication flow across a computer network is called', 'Socket', 'Pipe', 'port', 'machine', ' Socket is one end point in a two way communication link in the network. TCP layer can identify the application that data is destined to be sent by using the port number that is bound to socket.', 'No', 'No', 'No', '2021-11-16', 'A', 1),
(162, 'Computer Networks', 'Network Layers', 'Socket-style API for windows is called ____________', 'wsock', 'winsock', 'wins', 'sockwi', 'No', 'Winsock is a programming interface which deals with input output requests for internet applications in windows OS. It defines how windows network software should access network services', 'No', 'No', '2021-11-16', 'B', 1),
(163, 'Computer Networks', 'Network Layers', 'Which one of the following is a version of UDP with congestion control?', 'Datagram congestion control protocol', 'stream control transmission protocol', 'structured stream transport', 'user congestion control protocol', 'The datagram congestion control is a transport layer protocol which deals with reliable connection setup, teardown, congestion control, explicit congestion notification, and feature negotiation. It is used in modern day systems where there are really high chances of congestion. The protocol was last updated in the year 2008', 'No', 'No', 'No', '2021-11-16', 'A', 1),
(164, 'Computer Networks', 'Network Layers', ' A _____ is a TCP name for a transport service access point.', 'port', 'pipe', 'node ', 'protocol', ' A _____ is a TCP name for a transport service access point.', 'No', 'No', 'No', '2021-11-16', 'A', 1),
(165, 'Computer Networks', 'Network Layers', 'Transport layer protocols deals with ____________', 'application to application communication', 'process to process communication', 'node to node communication', ' man to man communication', 'No', 'No', 'No', 'No', '2021-11-16', 'B', 1),
(166, 'Computer Networks', 'Network Layers', 'Which of the following is a transport layer protocol?', ' stream control transmission protocol', 'internet control message protocol', 'neighbor discovery protocol', 'dynamic host configuration protocol', 'The Stream Control Transmission Protocol (SCTP) is a transport layer protocol used in networking system where streams of data are to be continuously transmitted between two connected network nodes. Some of the other transport layer protocols are RDP, RUDP, TCP, DCCP, UDP', 'No', 'No', 'No', '2021-11-16', 'A', 1),
(167, 'Artificial Intelligence', 'Introduction', ' First AI programming language is?', 'LISP', 'IPL', 'FORTRON', 'BASIC', 'The first practical and still most widely used AI programming language is the functional language Lisp developed by John McCarthy in the late 1950s.', 'Clifford Shaw of the Rand Corporation and Herbert Simon of Carnegie Mellon University developed their Information Processing Language (IPL), a computer language tailored for AI programming. ', 'No', 'No', '2021-11-16', 'B', 1),
(168, 'Artificial Intelligence', 'Introduction', 'Which generation of computers is associated with artificial intelligence?', '4', '5', '6', 'None', 'No', 'No', 'No', 'No', '2021-11-16', 'B', 1),
(169, 'Artificial Intelligence', 'Introduction', '___ is called the father of Artificial intelligence...', 'John McCarthy', 'Mames C Gosting', 'Dennis Ritchie', 'None', 'No', 'No', 'No', 'No', '2021-11-16', 'A', 1),
(170, 'Artificial Intelligence', 'Network Layers', 'What is a Web Crawler?', 'Simple reflex agent', 'Model based agent', 'Problem solving agent', 'Intelligent goal-based agent', 'No', 'No', 'No', 'No', '2021-11-16', 'A', 1),
(171, 'Artificial Intelligence', 'Introduction', 'Informed search strategy also called…', 'Simple Search', 'Online search', 'Heuristic Search', 'None of these', 'No', 'No', 'No', 'No', '2021-11-16', 'C', 1),
(172, 'Artificial Intelligence', 'Introduction', 'An agent is composed of…', 'Architecture and Program', 'Perception Sequence', 'Agent Function', 'Architecture', 'No', 'No', 'No', 'No', '2021-11-16', 'A', 1),
(173, 'Artificial Intelligence', 'Introduction', ' Zero sum game has ___ players?', 'Seven', 'Two', 'three ', 'Multiplayer', 'No', 'No', 'No', 'No', '2021-11-16', 'A', 1),
(174, 'Artificial Intelligence', 'Introduction', 'Values of alpha-beta search get updated', 'At the end', 'along the path of search', 'initial state itself', 'None of the mentioned', 'No', 'No', 'No', 'No', '2021-11-16', 'B', 1),
(175, 'Artificial Intelligence', 'Introduction', 'Calculate the feasibility of whole game tree used', 'Evaluation function', 'Alpha-beta pruning', 'Transposition', 'All of these', 'No', 'No', 'No', 'No', '2021-11-16', 'A', 1),
(176, 'Artificial Intelligence', 'Introduction', 'Which of the following is also called First order Logic?', 'Lower Order Calculus', ' First Order Predicate Calculus', 'Quantification Theory', 'All of these', 'No', 'No', 'No', 'No', '2021-11-16', 'D', 1),
(177, 'Data Structure and Algorithm', 'Search Algorithms ', 'Which of the following takes less memory?', 'Depth-First Search', 'Breadth-First Search', 'Optimal Search', 'Linear Search', 'No', 'No', 'No', 'No', '2021-11-16', 'A', 1),
(178, 'Artificial Intelligence', 'Introduction', 'Who coined the word ‘artificial intelligence’ in 1956 in a conference that was held at Dartmouth College?', 'David Levy', 'Hans Berliner', 'Joseph Weizenbaum', 'John McCarthy', 'No', 'No', 'No', 'No', '2021-11-16', 'B', 1),
(179, 'Artificial Intelligence', 'Introduction', 'LISP was created by', 'John McCarthy', 'Marvin Minsky', 'Alan Turing', 'Allen Hewell and Herbert Simon', 'No', 'No', 'No', 'No', '2021-11-16', 'A', 1),
(180, 'Artificial Intelligence', 'Introduction', 'The types of agents in artificial intelligence is…', '3', '4', '2', '1', 'No', 'No', 'No', 'No', '2021-11-16', 'B', 1),
(181, 'Operating System', 'Basic', ' What is the main function of the command interpreter?', 'to provide the interface between the API and application program', 'to handle the files in the operating system', 'to get and execute the next user-specified command', 'none of the mentioned', 'No', 'No', 'The main function of a command interpreter is to get and execute the next user-specified command. Command Interpreter checks for valid command and then runs that command else it will throw an error.', 'No', '2021-11-16', 'C', 1),
(182, 'Operating System', 'Basic', 'To access the services of the operating system, the interface is provided by the ___________', ' Library', 'System calls', 'Assembly instructions', 'API', 'No', 'To access services of the Operating System an interface is provided by the System Calls. Generally, these are functions written in C and C++. Open, Close, Read, Write are some of most prominently used system calls.', 'No', 'No', '2021-11-16', 'B', 1),
(183, 'Operating System', 'Basic', 'CPU scheduling is the basis of ___________', 'multiprogramming operating systems', ' larger memory sized systems', 'multiprocessor systems', 'none of the mentioned', 'No', 'No', 'No', 'No', '2021-11-16', 'A', 1),
(184, 'Operating System', 'Basic', 'Which one of the following is not true?', 'kernel remains in the memory during the entire computer session', 'kernel is made of various modules which can not be loaded in running operating system', 'kernel is the first part of the operating system to load into memory during booting', ' kernel is the program that constitutes the central core of the operating system', 'No', 'No', 'No', 'No', '2021-11-16', 'B', 1),
(185, 'Operating System', 'Basic', 'Which one of the following errors will be handle by the operating system?', ' lack of paper in printer', 'connection failure in the network', ' power failure', 'all of the mentioned', 'No', 'Kernel is the first program that is loaded in memory when OS is loading as well as it remains in memory till OS is running. Kernel is the core part of the OS which is responsible for managing resources, allowing multiple processes to use the resources and provide services to various processes. Kernel modules can be loaded and unloaded in run-time i.e. in running OS', 'No', 'No', '2021-11-16', 'D', 1),
(186, 'Operating System', 'Basic', 'Where is the operating system placed in the memory?', 'either low or high memory (depending on the location of interrupt vector)', 'in the low memory', 'in the high memory', 'none of the mentioned', 'No', 'No', 'No', 'No', '2021-11-16', 'A', 1),
(187, 'Operating System', 'Basic', ' If a process fails, most operating system write the error information to a ______', 'new file', 'another running process', 'log file', 'none of the mentioned', 'No', 'No', 'If a process fails, most operating systems write the error information to a log file. Log file is examined by the debugger, to find out what is the actual cause of that particular problem. Log file is useful for system programmers for correcting errors', 'No', '2021-11-16', 'C', 1),
(188, 'Operating System', 'Basic', 'Which one of the following is not a real time operating system?', 'RTLinux', 'Palm OS', 'QNX', 'VxWorks', 'No', 'VxWorks, QNX & RTLinux are real-time operating systems. Palm OS is a mobile operating system. Palm OS is developed for Personal Digital Assistants (PDAs).', 'No', 'No', '2021-11-16', 'B', 1),
(189, 'Operating System', 'Basic', 'What does OS X has?', 'monolithic kernel with modules', 'microkernel', 'monolithic kernal', 'hybrid kernel', 'No', 'No', 'No', 'OS X has a hybrid kernel. Hybrid kernel is a combination of two different kernels. OS X is developed by Apple and originally it is known as Mac OS X', '2021-11-16', 'D', 1),
(190, 'Operating System', 'Basic', 'In operating system, each process has its own __________', 'Open files', 'Pending alarms, signals and signal handlers', 'Address space and global variables', 'All of the mentioned', 'No', 'No', 'No', 'No', '2021-11-16', 'D', 1),
(191, 'Operating System', 'Basic', ' In a timeshare operating system, when the time slot assigned to a process is completed, the process switches from the current state to?', 'Suspended State ', 'Ready State', 'Terminated State', 'Blocked State', 'No', 'No', 'In a time-sharing operating system, when the time slot given to a process is completed, the process goes from the running state to the Ready State. In a time-sharing operating system, unit time is defined for sharing CPU, it is called a time quantum or time slice. If a process takes less than 1 time quantum, then the process itself releases the CPU', 'No', '2021-11-16', 'C', 1),
(192, 'Operating System', 'Basic', ' Cascading termination refers to the termination of all child processes if the parent process terminates ______', 'Normally or abnormally', 'Abnormally', 'Normally', 'None of the mentioned', 'No', 'No', 'No', 'No', '2021-11-16', 'A', 1),
(193, 'Operating System', 'Basic', ' When a process is in a “Blocked” state waiting for some I/O service. When the service is completed, it goes to the __________', 'Terminated state', 'Suspended state', 'Running state', 'Ready state', 'No', 'No', 'No', 'Suppose that a process is in “Blocked” state waiting for some I/O service. When the service is completed, it goes to the ready state. Process never goes directly to the running state from the waiting state. Only processes which are in ready state go to the running state whenever CPU allocated by operating system.', '2021-11-16', 'D', 1),
(194, 'Operating System', 'Basic', 'Transient operating system code is a code that ____________', ' stays in the memory always', 'never enters the memory space', 'comes and goes as needed', 'is not easily accessible', 'No', 'No', 'No', 'No', '2021-11-16', 'C', 1),
(195, 'Operating System', 'Basic', 'The portion of the process scheduler in an operating system that dispatches processes is concerned with ____________', 'assigning ready processes to waiting queue', 'assigning running processes to blocked queue', 'assigning ready processes to CPU', 'all of the mentioned', 'No', 'No', 'No', 'No', '2021-11-16', 'C', 1),
(196, 'Operating System', 'Basic', 'The FCFS algorithm is particularly troublesome for', 'operating systems', 'multiprocessor systems', 'time sharing systems', 'multiprogramming systems', 'No', 'No', 'No', 'No', '2021-11-16', 'D', 1),
(197, 'Operating System', 'Basic', ' For an effective operating system, when to check for deadlock?', 'every time a resource request is made at fixed time intervals', 'at random time intervals', 'a process started', 'none of the mentioned', 'No', 'No', 'No', 'No', '2021-11-16', 'n an effective operating system, we must verify the deadlock each time a request for resources is made at fixed time intervals.', 1);

-- --------------------------------------------------------

--
-- Table structure for table `chapters`
--

DROP TABLE IF EXISTS `chapters`;
CREATE TABLE IF NOT EXISTS `chapters` (
  `chapter_id` int NOT NULL AUTO_INCREMENT,
  `chapter_name` varchar(250) NOT NULL,
  PRIMARY KEY (`chapter_id`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `chapters`
--

INSERT INTO `chapters` (`chapter_id`, `chapter_name`) VALUES
(1, 'Operating System'),
(2, 'Software Engineering'),
(3, 'Database System'),
(4, 'Computer Organization and Architecture'),
(5, 'Computer Networks'),
(6, 'Artificial Intelligence'),
(7, 'Data Structure and Algorithm');

-- --------------------------------------------------------

--
-- Table structure for table `topics`
--

DROP TABLE IF EXISTS `topics`;
CREATE TABLE IF NOT EXISTS `topics` (
  `topic_id` int NOT NULL AUTO_INCREMENT,
  `topic_name` varchar(250) NOT NULL,
  PRIMARY KEY (`topic_id`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `topics`
--

INSERT INTO `topics` (`topic_id`, `topic_name`) VALUES
(1, 'Basic'),
(2, 'Process'),
(3, 'Memory Management'),
(4, 'Pipelining'),
(5, 'Cluster'),
(6, 'Scheduling'),
(7, 'Introduction'),
(8, 'Network Layers'),
(9, 'Search Algorithms ');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
